fly_bbs/__init__.py
from flask import Flask
from fly_bbs.configs import configs
from fly_bbs.controllers import config_blueprints
from fly_bbs.install_init import init as install_init
from fly_bbs.extensions import init_extensions
from fly_bbs.custom_functions import init_func
from fly_bbs import flask_objectid_converter


def create_app(config_name):
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'PyFly123'
    app.url_map.converters['ObjectId'] = flask_objectid_converter.ObjectIdConverter
    app.config.from_object(configs[config_name])
    init_extensions(app)
    config_blueprints(app)
    init_func(app)
    with app.app_context():
        install_init()
    return app

fly_bbs/controllers/bbs_index.py
from flask import Blueprint, render_template, session, jsonify, url_for, request, redirect
from flask_login import current_user
from bson import ObjectId
from datetime import datetime
from pymongo import DESCENDING
from .. import code_msg
from ..forms import PostForm
from ..models import R, BaseResult, Page
from ..utils import gen_verify_num, verify_num
from ..extensions import mongo, whoosh_searcher
from ..db_utils import get_page, find_one
from whoosh import qparser, sorting
from whoosh.query import *


bbs_index = Blueprint("bbs_index", __name__, template_folder='templates')


@bbs_index.route('/')
@bbs_index.route('/page/<int:pn>/size/<int:size>')
@bbs_index.route('/page/<int:pn>')
@bbs_index.route("/catalog/<ObjectId:catalog_id>")
@bbs_index.route("/catalog/<ObjectId:catalog_id>/page/<int:pn>")
@bbs_index.route("/catalog/<ObjectId:catalog_id>/page/<int:pn>/size/<int:size>")
def index(pn=1, size=10, catalog_id=None):
    sort_key = request.values.get('sort_key', '_id')
    sort_by = (sort_key, DESCENDING)
    post_type = request.values.get('type')
    filter1 = {}
    if post_type == 'not_closed':
        filter1['is_closed'] = {'$ne': True}
    if post_type == 'is_closed':
        filter1['is_closed'] = True
    if post_type == 'is_cream':
        filter1['is_cream'] = True
    if catalog_id:
        filter1['catalog_id'] = catalog_id
    page = get_page('posts', pn=pn, filter1=filter1, size=size,
                    sort_by=sort_by)
    return render_template('post_list.html', is_index=catalog_id is None, page=page,
                           sort_key=sort_key, catalog_id=catalog_id,
                           post_type=post_type)


@bbs_index.route('/add', methods=['GET', 'POST'])
@bbs_index.route('/edit/<ObjectId:post_id>', methods=['GET', 'POST'])
def add(post_id=None):
    form = PostForm()
    if form.is_submitted():
        if not form.validate():
            return jsonify(BaseResult(1, str(form.errors)))
        try:
            verify_num(form.vercode.data)
        except Exception as e:
            return '<h1>{}</h1>'.format(e), 404
        user = current_user.user
        if not user.get('is_active'):
            return jsonify(code_msg.USER_UN_ACTIVE_OR_DISABLED)
        user_coin = user.get('coin', 0)
        if form.reward.data > user_coin:
            msg = '悬赏金币不能大于拥有的金币，当前账号金币为：{}'.format(user_coin)
            return jsonify(R.ok(msg=msg))
        post = {
            'title': form.title.data,
            'catalog_id': ObjectId(form.catalog_id.data),
            'is_closed': False,
            'content': form.content.data
        }
        msg = '发帖成功'
        reward = form.reward.data
        if post_id:
            post['modified_at'] = datetime.utcnow()
            mongo.db.posts.update_one({'_id': post_id}, {'$set': post})
            msg = '修改成功'
        else:
            post['created_at'] = datetime.utcnow()
            post['reward'] = reward
            post['user_id'] = user['_id']
            mongo.db.users.update_one({'_id': user['_id']},
                                      {'$inc': {'coin': -reward}})
            print('Before: %s' % post)
            mongo.db.posts.insert_one(post)
            print('After: %s' % post)
            post_id = post['_id']
        return jsonify(R.ok(msg).put('action', url_for('.index')))
    ver_code = gen_verify_num()
    post = None
    title = '发布帖子'
    if post_id:
        post = mongo.db.posts.find_one_or_404({'_id': post_id})
        title = '编辑帖子'
    return render_template('jie/add.html', page_name='jie', form=form, ver_code=ver_code['question'],
                           is_add=(post_id is None), post=post, title=title)


@bbs_index.route('/post/<ObjectId:post_id>/')
@bbs_index.route('/post/<ObjectId:post_id>/page/<int:pn>/')
def post_detail(post_id, pn=1):
    post = mongo.db.posts.find_one_or_404({'_id': post_id})
    if post:
        post['view_count'] = post.get('view_count', 0) + 1
        mongo.db.posts.save(post)
    post['user'] = find_one('users', {'_id': post['user_id']}) or {}
    page = get_page('comments', pn=pn, size=10, filter1={'post_id': post_id},
                    sort_by=('is_adopted', -1))
    return render_template('jie/detail.html', post=post, title=['title'],
                           page_name='jie', comment_page=page, catalog_id=post['catalog_id'])


@bbs_index.route('/comment/<ObjectId:comment_id>/')
def jump_comment(comment_id):
    comment = mongo.db.comments.find_one_or_404({'_id': comment_id})
    post_id = comment['post_id']
    pn = 1
    if not comment.get('is_adopted', False):
        comment_index = mongo.db.comments.count(
            {
                'post_id': post_id, '_id': {'$lt': comment_id}
            }
        )
        pn = comment_index // 10
        if pn == 0 or comment_index % 10 != 0:
            pn += 1
    return redirect(
        url_for('bbs_index.post_detail', post_id=post_id, pn=pn) + '#item-' + str(comment_id)
    )


@bbs_index.route('/refresh/indexes')
def refresh_indexes():
    name = request.values.get('name')
    whoosh_searcher.clear(name)
    writer = whoosh_searcher.get_writer(name)
    for item in mongo.db[name].find(
            {},
            ['_id', 'title', 'content', 'create_at', 'user_id', 'catalog_id']):
        item['obj_id'] = str(item['_id'])
        item['user_id'] = str(item['user_id'])
        item['catalog_id'] = str(item['catalog_id'])
        item.pop('_id')
        writer.add_document(**item)
    writer.commit()
    return ''


@bbs_index.route('/search')
@bbs_index.route('/search/page/<int:pn>/')
def post_search(pn=1, size=10):
    keyword = request.values.get('kw')
    if keyword is None:
        return render_template(
            'search/list.html', title='搜索', message='搜索关键字不能为空！', page=None
        )
    whoosh_searcher.clear('posts')
    writer = whoosh_searcher.get_writer('posts')
    for item in mongo.db['posts'].find(
        {},
        ['_id', 'title', 'content', 'create_at', 'user_id', 'catalog_id']
    ):
        item['obj_id'] = str(item['_id'])
        item['user_id'] = str(item['user_id'])
        item['catalog_id'] = str(item['catalog_id'])
        item.pop('_id')
        writer.add_document(**item)
    writer.commit()
    with whoosh_searcher.get_searcher('posts') as searcher:
        parser = qparser.MultifieldParser(
            ['title', 'content'],
            whoosh_searcher.get_index('posts').schema
        )
        q = parser.parse(keyword)
        print('q: ', q)
        result = searcher.search_page(
            q, pagenum=pn, pagelen=size, sortedby=sorting.ScoreFacet()
        )
        result_list = [x.fields() for x in result.results]
        # import pdb
        # pdb.set_trace()
        page = Page(
            pn, size, result=result_list, has_more=result.pagecount > pn,
            page_count=result.pagecount, total=result.total)
    return render_template(
        'search/list.html', title=keyword + '搜索结果', page=page, kw=keyword
    )

fly_bbs/controllers/user_view.py
import json
from bson import ObjectId
from datetime import datetime
from flask import Blueprint, abort, render_template, request, jsonify, redirect, url_for, session
from ..models import User
from ..extensions import mongo
from .. import utils
from werkzeug.security import generate_password_hash
from random import randint
from ..forms import RegisterForm, LoginForm
from flask_login import login_user, logout_user, login_required, current_user
from .. import db_utils
from .. import models
from .. import forms
from .. import code_msg


user_view = Blueprint('user', __name__, url_prefix='/user', template_folder='templates')


class MyEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        if isinstance(o, datetime):
            return o.isoformat()
        super().default(o)


def send_active_email(username, user_id, email, is_forget=False):
    code = mongo.db.active_codes.insert_one({'user_id': user_id})
    if is_forget:
        body = render_template(
            'email/user_repwd.html',
            url=url_for('user.user_pass_forget', code=code.inserted_id, _external=True)
        )
        utils.send_email(email, '重置密码', body=body)
        return
    body = render_template(
        'email/user_active.html', username=username,
        url=url_for('user.user_active', code=code.inserted_id, _external=True)
    )
    utils.send_email(email, '账号激活', body=body)


@user_view.route('/')
def home():
    users = list(mongo.db.users.find())
    print(users)
    return json.dumps(users, cls=MyEncoder, ensure_ascii=False)


@user_view.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.is_submitted():
        if not form.validate():
            return jsonify({'status': 50001, 'msg': str(form.errors)})
        vercode = form.vercode.data
        try:
            utils.verify_num(vercode)
        except Exception as e:
            return '<h1>{}</h1>'.format(e), 404
        user = mongo.db.users.find_one({'email': form.email.data})
        if not user:
            return jsonify({'status': 50102, 'msg': '用户不存在'})
        if not User.validate_login(user['password'], form.password.data):
            return jsonify({'status': 50000, 'msg': '密码错误'})
        if not user.get('is_active'):
            return jsonify({'status': 443, 'msg': '账号未激活'})
        login_user(User(user))
        return redirect(url_for('bbs_index.index'))
    ver_code = utils.gen_verify_num()
    return render_template('user/login.html', ver_code=ver_code['question'], form=form)


@user_view.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('bbs_index.index'))


@user_view.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.is_submitted():
        if not form.validate():
            return jsonify({'status': 50001, 'msg': str(form.errors)})
        try:
            utils.verify_num(form.vercode.data)
        except Exception as e:
            return '<h1>{}</h1>'.format(e), 404
        user = mongo.db.users.find_one({'email': form.email.data})
        if user:
            return jsonify({'status': 50000, 'msg': '该邮箱已经注册'})
        user = {
            'is_active': False,
            'coin': 0,
            'email': form.email.data,
            'username': form.username.data,
            'vip': 0,
            'reply_count': 0,
            'avatar': url_for('static',
                filename='images/avatar/{}.jpg'.format(randint(0, 12))),
            'password': generate_password_hash(form.password.data),
            'created_at': datetime.utcnow()
        }
        insert_result = mongo.db.users.insert_one(user)
        # utils.send_email(form.email.data, '你激活了',
        #                  body='你已经成功注册了账号，同时完成了发送邮件功能！')
        # mongo.db.users.update_one(
        #     {'username': form.username.data}, {'$set': {'is_active': True}}
        # )
        send_active_email(form.username.data, insert_result.inserted_id, form.email.data)
        return redirect(url_for('.login'))
    ver_code = utils.gen_verify_num()
    return render_template(
        'user/register.html',
        ver_code=ver_code['question'],
        form=form
    )


@user_view.route('/<ObjectId:user_id>')
@login_required
def user_home(user_id):
    user = mongo.db.users.find_one_or_404({'_id': user_id})
    return render_template('user/home.html', user=user)


@user_view.route('/messsage')
@user_view.route('/message/page/<int:pn>')
@login_required
def user_message(pn=1):
    user = current_user.user
    if user.get('unread', 0) > 0:
        mongo.db.users.update({'_id': user['_id']}, {'$set': {'unread': 0}})
    message_page = db_utils.get_page(
        'messages', pn, filter1={'user_id': user['_id']}, sort_by=('_id', -1)
    )
    return render_template(
        'user/message.html', user_page='message', page_name='user', page=message_page
    )


@user_view.route('/message/remove', methods=['POST'])
@login_required
def remove_message():
    user = current_user.user
    if request.values.get('all') == 'true':
        mongo.db.messages.delete_many({'user_id': user['_id']})
    elif request.values.get('id'):
        msg_id = ObjectId(request.values.get('id'))
        mongo.db.messages.delete_one({'_id': msg_id})
    return jsonify(models.BaseResult())


@user_view.route('/set', methods=['GET', 'POST'])
@login_required
def user_set():
    if request.method == 'POST':
        include_keys = ['username', 'avatar', 'desc', 'city', 'sex']
        data = request.values
        update_data = {}
        for key in data.keys():
            if key in include_keys:
                update_data[key] = data.get(key)
        mongo.db.users.update(
            {'_id': current_user.user['_id']}, {'$set': update_data}
        )
        return jsonify('修改成功')
    return render_template(
        'user/set.html', user_page='set', page_name='user', title='基本设置'
    )


# @user_view.route('/repass', methods=['POST'])
# def user_repass():
#     if not current_user.is_authenticated:
#         redirect(url_for('user.login'))
#     pwd_form = forms.ChangePassWordForm()
#     if not pwd_form.validate():
#         return jsonify(
#             models.R.fail(
#                 code_msg.PARAM_ERROR.get_msg(),
#                 str(pwd_form.errors)
#             )
#         )
#     nowpassword = pwd_form.nowpassword.data
#     password = pwd_form.password.data
#     user = current_user.user
#     if not models.User.validate_login(user['password'], nowpassword):
#         raise Exception(code_msg.PASSWORD_ERROR)
#     mongo.db.users.update(
#         {'_id': user['_id']}, {'$set': {'password': generate_password_hash(password)}}
#     )
#     return jsonify(models.R.ok())


@user_view.route('/active', methods=['GET', 'POST'])
def user_active():
    if request.method == 'GET':
        code = request.values.get('code')
        if code:
            user_id = mongo.db.active_codes.find_one(
                {'_id': ObjectId(code)}
            ).get('user_id')
            if user_id:
                mongo.db.active_codes.delete_many({'user_id': ObjectId(user_id)})
                mongo.db.users.update(
                    {'_id': user_id}, {'$set': {'is_active': True}}
                )
                user = mongo.db.users.find_one({'_id': ObjectId(user_id)})
                login_user(models.User(user))
                return render_template('user/activate.html')
        if not current_user.is_authenticated:
            abort(403)
        return render_template('user/activate.html')
    user = current_user.user
    mongo.db.active_codes.delete_many({'user_id': ObjectId(user['_id'])})
    send_active_email(user['username'], user['_id'], user['email'])
    return jsonify(code_msg.RE_ACTIVATE_MAIL_SEND.put('action', url_for('user.user_active')))


@user_view.route('/forget', methods=['POST', 'GET'])
def user_pass_forget():
    code = request.args.get('code')
    mail_form = forms.SendForgetMailForm()
    if mail_form.is_submitted():
        if not mail_form.validate():
            return jsonify(
                models.R.fail(
                    code_msg.PARAM_ERROR.get_msg(),
                    str(mail_form.errors)
                )
            )
        email = mail_form.email.data
        ver_code = mail_form.vercode.data
        utils.verify_num(ver_code)
        user = mongo.db.users.find_one({'email': email})
        if not user:
            return jsonify(code_msg.USER_NOT_EXIST)
        send_active_email(user['username'], user_id=user['_id'], email=email, is_forget=True)
        return jsonify(code_msg.RE_PWD_MAIL_SEND.put('action', url_for('user.login')))
    has_code = False
    user = None
    if code:
        active_code = mongo.db.active_codes.find_one({'_id': ObjectId(code)})
        if not active_code:
            return render_template(
                'user/forget.html', page_name='user', has_code=True, code_invalid=True
            )
        has_code = True
        user = mongo.db.users.find_one({'_id': active_code['user_id']})
    ver_code = utils.gen_verify_num()

    return render_template(
        'user/forget.html', page_name='user', ver_code=ver_code['question'],
        code=code, has_code=has_code, user=user
    )


@user_view.route('/repass', methods=['POST'])
def user_repass():
    if 'email' in request.values:
        pwd_form = forms.ForgetPasswordForm()
        if not pwd_form.validate():
            return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(pwd_form.errors)))
        email = pwd_form.email.data
        ver_code = pwd_form.vercode.data
        code = pwd_form.code.data
        password = pwd_form.password.data
        utils.verify_num(ver_code)
        active_code = mongo.db.active_codes.find_one_or_404({'_id': ObjectId(code)})
        mongo.db.active_codes.delete_one({'_id': ObjectId(code)})
        user = mongo.db.users.update(

fly_bbs/plugins/__init__.py
from .whoosh import WhooshSearcher

fly_bbs/templates/user/activate.html
{% extends 'base.html' %}

{% block body %}
  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>

  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  <div class="fly-panel fly-panel-user" pad20>
    <div class="layui-tab layui-tab-brief" lay-filter="user">
      <ul class="layui-tab-title">
        <li class="layui-this">
          激活邮箱
        </li>
      </ul>
      <div class="layui-tab-content" id="LAY_ucm" style="padding: 20px 0;">
        <ul class="layui-form">
          <li class="layui-form-li">
            <label for="activate">您的邮箱：</label>
            <span class="layui-form-text">{{ current_user.user.email }}
              {% if current_user.user.is_active %}
              <em style="color:#999;">（已成功激活）</em>
              {% else %}
              <em style="color:#c00;">（尚未激活）</em>
              {% endif %}
            </span>
          </li>
          <li class="layui-form-li" style="margin-top: 20px; line-height: 26px;">
            <div>
              1. 如果您未收到邮件，或激活链接失效，您可以
              <a class="layui-form-a" style="color:#4f99cf;" id="LAY-activate" href="javascript:;" email="{{current_user.user.email}}">重新发送邮件</a>，或者
              <a class="layui-form-a" style="color:#4f99cf;" href="set.html">更换邮箱</a>；
            </div>
            <div>
              2. 如果您始终没有收到 Fly 发送的邮件，请注意查看您邮箱中的垃圾邮件；
            </div>
            <div>
              3. 如果你实在无法激活邮件，您还可以联系：chzix@foxmail.com
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

fly_bbs/templates/user/forget.html
{% extends 'base.html' %} {% block body %}
<div class="layui-container fly-marginTop">
  <div class="fly-panel fly-panel-user" pad20>
    <div class="layui-tab layui-tab-brief" lay-filter="user">
      <ul class="layui-tab-title">
        <li><a href="{{ url_for('user.login') }}">登入</a></li>
        <li class="layui-this">找回密码<!--重置密码--></li>
      </ul>
      <div
        class="layui-form layui-tab-content"
        id="LAY_ucm"
        style="padding: 20px 0;"
      >
        <div class="layui-tab-item layui-show">
          {# has_code 为真时，说明用户是从邮箱里点击重置密码访问的 #} {% if
          has_code %} {% if code_invalid %}
          <div class="fly-error">该重置密码链接已失效，请重新校验您的信息</div>
          {% else %}
          <div class="fly-msg">{{ user.username }}，请重置您的密码</div>
          <div class="layui-form layui-form-pane" style="margin-top: 30px;">
            <form action="{{ url_for('user.user_repass') }}" method="post">
              <div class="layui-form-item">
                <label for="L_pass" class="layui-form-label">密码</label>
                <div class="layui-input-inline">
                  <input
                    type="password"
                    id="L_pass"
                    name="password"
                    required
                    lay-verify="required"
                    autocomplete="off"
                    class="layui-input"
                  />
                </div>
                <div class="layui-form-mid layui-word-aux">6到16个字符</div>
              </div>
              <div class="layui-form-item">
                <label for="L_repass" class="layui-form-label">确认密码</label>
                <div class="layui-input-inline">
                  <input
                    type="password"
                    id="L_repass"
                    name="repassword"
                    required
                    lay-verify="required"
                    autocomplete="off"
                    class="layui-input"
                  />
                </div>
              </div>
              <div class="layui-form-item">
                <label for="L_vercode" class="layui-form-label">人类验证</label>
                <div class="layui-input-inline">
                  <input
                    type="text"
                    id="L_vercode"
                    name="vercode"
                    required
                    lay-verify="required"
                    placeholder="请回答后面的问题"
                    autocomplete="off"
                    class="layui-input"
                  />
                </div>
                <div class="layui-form-mid">
                  <span style="color: #c00;">{{ ver_code }}</span>
                </div>
              </div>
              <div class="layui-form-item">
                <input type="hidden" name="code" value="{{ code }}" />
                <input type="hidden" name="email" value="{{ user.email }}" />
                <button class="layui-btn" alert="1" lay-filter="*" lay-submit>
                  提交
                </button>
              </div>
            </form>
          </div>
          {% endif %} {# 输入忘记密码账号的邮箱页面 #} {% else %}
          <div class="layui-form layui-form-pane">
            <form method="post">
              <div class="layui-form-item">
                <label for="L_email" class="layui-form-label">邮箱</label>
                <div class="layui-input-inline">
                  <input
                    type="text"
                    id="L_email"
                    name="email"
                    required
                    lay-verify="required|email"
                    autocomplete="off"
                    class="layui-input"
                  />
                </div>
              </div>
              <div class="layui-form-item">
                <label for="L_vercode" class="layui-form-label">人类验证</label>
                <div class="layui-input-inline">
                  <input
                    type="text"
                    id="L_vercode"
                    name="vercode"
                    required
                    lay-verify="required"
                    placeholder="请回答后面的问题"
                    autocomplete="off"
                    class="layui-input"
                  />
                </div>
                <div class="layui-form-mid">
                  <span style="color: #c00;">{{ ver_code }}</span>
                </div>
              </div>
              <div class="layui-form-item">
                <button class="layui-btn" alert="1" lay-filter="*" lay-submit>
                  提交
                </button>
              </div>
            </form>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

fly_bbs/templates/user/home.html
{% extends 'base.html' %} {% block body %}
<div class="fly-home fly-panel">
  <img src="{{ user.avatar }}" alt="{{ user.username }}" />
  {% if user.renzheng %}
  <i class="iconfont icon-renzheng" title="社区认证"></i>
  {% endif %}
  <h1>
    {{ user.username }} {% if user.sex == '0' %}
    <i class="iconfont icon-nan"></i>
    {% else %}
    <i class="iconfont icon-nv"></i>
    {% endif %} {% if user.get('vip', 0) > 0 %}
    <i class="layui-badge fly-badge-vip">VIP{{ user.vip }}</i>
    {% endif %} {% if user.is_admin %}
    <span style="color:#c00">(管理员)</span>
    {% endif %} {% if user.is_disabled %}
    <span style="color:#999">（该号已被封）</span>
    {% endif %}
  </h1>
  {% if user.renzheng %}
  <p style="padding: 10px 0; color: #5FB878;">认证信息：{{ user.renzheng }}</p>
  {% endif %}
  <p class="fly-home-info">
    <i class="iconfont icon-jifen" title="金币"></i
    ><span style="color: #FF7200;">{{ user.get('coin', 0) }} 金币</span>
    <i class="iconfont icon-shijian"></i
    ><span>{{ user.get('create_at')|mongo_date_str or '时间保密 ' }} 加入</span>
    <i class="iconfont icon-chengshi"></i
    ><span>来自{{ user.get('city') or '保密的火星' }}</span>
  </p>
  <p class="fly-home-sign">({{ user.get('desc') or '这家伙懒得留下签名' }})</p>
</div>
<div class="layui-container">
  <div class="layui-row layui-col-space15">
    <div class="layui-col-md6 fly-home-jie">
      <div class="fly-panel">
        <h3 class="fly-panel-title">{{ user.username }} 最近的帖子</h3>
        <ul class="jie-row">
          {% for item in get_list('posts', size=10, sort_by=('_id', -1),
          filter1={'user_id': user._id}) %}
          <li>
            {% if item.is_cream %}
            <span class="fly-jing">精</span>
            {% endif %}
            <a
              href="{{ url_for('bbs_index.post_detail', post_id=item._id) }}"
              class="jie-title"
            >
              {{ item.title }}</a
            >
            <i>{{ item.create_at|mongo_date_str }}</i>
            <em class="layui-hide-xs"
              >{{ item.get('view_count', 0) }}阅/{{ item.get('comment_count', 0)
              }}答</em
            >
          </li>
          {% else %}
          <div
            class="fly-none"
            style="min-height: 50px; padding:30px 0; height:auto;"
          >
            <i style="font-size:14px;">没有发表任何帖子</i>
          </div>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="layui-col-md6 fly-home-da">
      <div class="fly-panel">
        <h3 class="fly-panel-title">{{ user.username }} 最近的回帖</h3>
        <ul class="home-jieda">
          {% for item in get_list('comments', size=10, sort_by=('_id', -1),
          filter1={'user_id': user._id}) %} {% set
          item_post=mongo_find_one('posts', {'_id': item.post_id}) %}
          <li>
            <p>
              <span>{{ item.create_at|mongo_date_str }}</span>
              在<a
                href="{{ url_for('bbs_index.jump_comment', comment_id=item._id) }}"
                target="_blank"
                >{{ item_post.title or '(已删除)' }}</a
              >中回答：
            </p>
            <div class="home-dacontent">
              {{ item.content }}
            </div>
          </li>
          {% else %}
          <div
            class="fly-none"
            style="min-height: 50px; padding:30px 0; height:auto;"
          >
            <i style="font-size:14px;">没有发表任何回帖</i>
          </div>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block fly_use %} .use(['fly', 'face'], function(){ var $ =
layui.$ ,fly = layui.fly; $('.home-dacontent').each(function(){ var othis =
$(this), html = othis.html(); othis.html(fly.content(html)); }); }); {% endblock
%}

fly_bbs/templates/user/user_active.html
激活{{ get_option('title').val or 'PyFly' }}的账号{{ username }}，如非本人操作请忽视， 请点击下面的链接重置您的密码，如果无法点击可复制粘贴到浏览器地址栏打开：

账号激活链接：{{ url }}

fly_bbs/templates/user/user_base.html
{% extends 'base.html' %} {% block body %}
<div class="layui-container fly-marginTop fly-user-main">
  <ul class="layui-nav layui-nav-tree layui-inline" lay-filter="user">
    <li class="layui-nav-item">
      <a href="{{ url_for('user.user_home', user_id=current_user.user._id) }}">
        <i class="layui-icon">&#xe609;</i>
        我的主页
      </a>
    </li>
    {#
    <li class="layui-nav-item {{ 'layui-this' if user_page == 'posts' }}">
      <a href="{{ url_for('user.user_posts') }}">
        <i class="layui-icon">&#xe612;</i>
        我的帖子
      </a>
    </li>
    #}
    <li class="layui-nav-item {{ 'layui-this' if user_page == 'set' }}">
      <a href="{{ url_for('user.user_set') }}">
        <i class="layui-icon">&#xe620;</i>
        基本设置
      </a>
    </li>
    <li class="layui-nav-item {{ 'layui-this' if user_page == 'message' }}">
      <a href="{{ url_for('user.user_message') }}">
        <i class="layui-icon">&#xe611;</i>
        我的消息
      </a>
    </li>
  </ul>
  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  <div class="site-tree-mobile layui-hide">
    <i class="layui-icon">&#xe602;</i>
  </div>
  <div class="site-mobile-shade"></div>
  <div class="fly-panel fly-panel-user" pad20>
    {% block content %} {% endblock %}
  </div>
</div>
{% endblock %}