fly_bbs/__init__.py
from flask import Flask
from fly_bbs.configs import configs
from fly_bbs.controllers import config_blueprints
from fly_bbs.install_init import init as install_init
from fly_bbs.extensions import init_extensions
from fly_bbs.custom_functions import init_func
from fly_bbs import flask_objectid_converter


def create_app(config_name):
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'PyFly123'
    app.url_map.converters['ObjectId'] = flask_objectid_converter.ObjectIdConverter
    app.config.from_object(configs[config_name])
    init_extensions(app)
    config_blueprints(app)
    init_func(app)
    with app.app_context():
        install_init()
    return app

fly_bbs/controllers/bbs_index.py
from flask import Blueprint, render_template, session, jsonify, url_for, request, redirect
from flask_login import current_user
from bson import ObjectId
from datetime import datetime
from pymongo import DESCENDING
from .. import code_msg
from ..forms import PostForm
from ..models import R, BaseResult, Page
from ..utils import gen_verify_num, verify_num
from ..extensions import mongo, whoosh_searcher
from ..db_utils import get_page, find_one
from whoosh import qparser, sorting
from whoosh.query import *


bbs_index = Blueprint("bbs_index", __name__, template_folder='templates')


@bbs_index.route('/')
@bbs_index.route('/page/<int:pn>/size/<int:size>')
@bbs_index.route('/page/<int:pn>')
@bbs_index.route("/catalog/<ObjectId:catalog_id>")
@bbs_index.route("/catalog/<ObjectId:catalog_id>/page/<int:pn>")
@bbs_index.route("/catalog/<ObjectId:catalog_id>/page/<int:pn>/size/<int:size>")
def index(pn=1, size=10, catalog_id=None):
    sort_key = request.values.get('sort_key', '_id')
    sort_by = (sort_key, DESCENDING)
    post_type = request.values.get('type')
    filter1 = {}
    if post_type == 'not_closed':
        filter1['is_closed'] = {'$ne': True}
    if post_type == 'is_closed':
        filter1['is_closed'] = True
    if post_type == 'is_cream':
        filter1['is_cream'] = True
    if catalog_id:
        filter1['catalog_id'] = catalog_id
    page = get_page('posts', pn=pn, filter1=filter1, size=size,
                    sort_by=sort_by)
    return render_template('post_list.html', is_index=catalog_id is None, page=page,
                           sort_key=sort_key, catalog_id=catalog_id,
                           post_type=post_type)


@bbs_index.route('/add', methods=['GET', 'POST'])
@bbs_index.route('/edit/<ObjectId:post_id>', methods=['GET', 'POST'])
def add(post_id=None):
    form = PostForm()
    if form.is_submitted():
        if not form.validate():
            return jsonify(BaseResult(1, str(form.errors)))
        try:
            verify_num(form.vercode.data)
        except Exception as e:
            return '<h1>{}</h1>'.format(e), 404
        user = current_user.user
        if not user.get('is_active'):
            return jsonify(code_msg.USER_UN_ACTIVE_OR_DISABLED)
        user_coin = user.get('coin', 0)
        if form.reward.data > user_coin:
            msg = '悬赏金币不能大于拥有的金币，当前账号金币为：{}'.format(user_coin)
            return jsonify(R.ok(msg=msg))
        post = {
            'title': form.title.data,
            'catalog_id': ObjectId(form.catalog_id.data),
            'is_closed': False,
            'content': form.content.data
        }
        msg = '发帖成功'
        reward = form.reward.data
        if post_id:
            post['modified_at'] = datetime.utcnow()
            mongo.db.posts.update_one({'_id': post_id}, {'$set': post})
            msg = '修改成功'
        else:
            post['created_at'] = datetime.utcnow()
            post['reward'] = reward
            post['user_id'] = user['_id']
            mongo.db.users.update_one({'_id': user['_id']},
                                      {'$inc': {'coin': -reward}})
            print('Before: %s' % post)
            mongo.db.posts.insert_one(post)
            print('After: %s' % post)
            post_id = post['_id']
        return jsonify(R.ok(msg).put('action', url_for('.index')))
    ver_code = gen_verify_num()
    post = None
    title = '发布帖子'
    if post_id:
        post = mongo.db.posts.find_one_or_404({'_id': post_id})
        title = '编辑帖子'
    return render_template('jie/add.html', page_name='jie', form=form, ver_code=ver_code['question'],
                           is_add=(post_id is None), post=post, title=title)


@bbs_index.route('/post/<ObjectId:post_id>/')
@bbs_index.route('/post/<ObjectId:post_id>/page/<int:pn>/')
def post_detail(post_id, pn=1):
    post = mongo.db.posts.find_one_or_404({'_id': post_id})
    if post:
        post['view_count'] = post.get('view_count', 0) + 1
        mongo.db.posts.save(post)
    post['user'] = find_one('users', {'_id': post['user_id']}) or {}
    page = get_page('comments', pn=pn, size=10, filter1={'post_id': post_id},
                    sort_by=('is_adopted', -1))
    return render_template('jie/detail.html', post=post, title=['title'],
                           page_name='jie', comment_page=page, catalog_id=post['catalog_id'])


@bbs_index.route('/comment/<ObjectId:comment_id>/')
def jump_comment(comment_id):
    comment = mongo.db.comments.find_one_or_404({'_id': comment_id})
    post_id = comment['post_id']
    pn = 1
    if not comment.get('is_adopted', False):
        comment_index = mongo.db.comments.count(
            {
                'post_id': post_id, '_id': {'$lt': comment_id}
            }
        )
        pn = comment_index // 10
        if pn == 0 or comment_index % 10 != 0:
            pn += 1
    return redirect(
        url_for('bbs_index.post_detail', post_id=post_id, pn=pn) + '#item-' + str(comment_id)
    )


@bbs_index.route('/refresh/indexes')
def refresh_indexes():
    name = request.values.get('name')
    whoosh_searcher.clear(name)
    writer = whoosh_searcher.get_writer(name)
    for item in mongo.db[name].find(
            {},
            ['_id', 'title', 'content', 'create_at', 'user_id', 'catalog_id']):
        item['obj_id'] = str(item['_id'])
        item['user_id'] = str(item['user_id'])
        item['catalog_id'] = str(item['catalog_id'])
        item.pop('_id')
        writer.add_document(**item)
    writer.commit()
    return ''


@bbs_index.route('/search')
@bbs_index.route('/search/page/<int:pn>/')
def post_search(pn=1, size=10):
    keyword = request.values.get('kw')
    if keyword is None:
        return render_template(
            'search/list.html', title='搜索', message='搜索关键字不能为空！', page=None
        )
    whoosh_searcher.clear('posts')
    writer = whoosh_searcher.get_writer('posts')
    for item in mongo.db['posts'].find(
        {},
        ['_id', 'title', 'content', 'create_at', 'user_id', 'catalog_id']
    ):
        item['obj_id'] = str(item['_id'])
        item['user_id'] = str(item['user_id'])
        item['catalog_id'] = str(item['catalog_id'])
        item.pop('_id')
        writer.add_document(**item)
    writer.commit()
    with whoosh_searcher.get_searcher('posts') as searcher:
        parser = qparser.MultifieldParser(
            ['title', 'content'],
            whoosh_searcher.get_index('posts').schema
        )
        q = parser.parse(keyword)
        print('q: ', q)
        result = searcher.search_page(
            q, pagenum=pn, pagelen=size, sortedby=sorting.ScoreFacet()
        )
        result_list = [x.fields() for x in result.results]
        # import pdb
        # pdb.set_trace()
        page = Page(
            pn, size, result=result_list, has_more=result.pagecount > pn,
            page_count=result.pagecount, total=result.total)
    return render_template(
        'search/list.html', title=keyword + '搜索结果', page=page, kw=keyword
    )

fly_bbs/controllers/user_view.py
import json
from bson import ObjectId
from datetime import datetime
from flask import Blueprint, abort, render_template, request, jsonify, redirect, url_for, session
from ..models import User
from ..extensions import mongo
from .. import utils
from werkzeug.security import generate_password_hash
from random import randint
from ..forms import RegisterForm, LoginForm
from flask_login import login_user, logout_user, login_required, current_user
from .. import db_utils
from .. import models
from .. import forms
from .. import code_msg


user_view = Blueprint('user', __name__, url_prefix='/user', template_folder='templates')


class MyEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        if isinstance(o, datetime):
            return o.isoformat()
        super().default(o)


def send_active_email(username, user_id, email, is_forget=False):
    code = mongo.db.active_codes.insert_one({'user_id': user_id})
    if is_forget:
        body = render_template(
            'email/user_repwd.html',
            url=url_for('user.user_pass_forget', code=code.inserted_id, _external=True)
        )
        utils.send_email(email, '重置密码', body=body)
        return
    body = render_template(
        'email/user_active.html', username=username,
        url=url_for('user.user_active', code=code.inserted_id, _external=True)
    )
    utils.send_email(email, '账号激活', body=body)


@user_view.route('/')
def home():
    users = list(mongo.db.users.find())
    print(users)
    return json.dumps(users, cls=MyEncoder, ensure_ascii=False)


@user_view.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.is_submitted():
        if not form.validate():
            return jsonify({'status': 50001, 'msg': str(form.errors)})
        vercode = form.vercode.data
        try:
            utils.verify_num(vercode)
        except Exception as e:
            return '<h1>{}</h1>'.format(e), 404
        user = mongo.db.users.find_one({'email': form.email.data})
        if not user:
            return jsonify({'status': 50102, 'msg': '用户不存在'})
        if not User.validate_login(user['password'], form.password.data):
            return jsonify({'status': 50000, 'msg': '密码错误'})
        if not user.get('is_active'):
            return jsonify({'status': 443, 'msg': '账号未激活'})
        login_user(User(user))
        return redirect(url_for('bbs_index.index'))
    ver_code = utils.gen_verify_num()
    return render_template('user/login.html', ver_code=ver_code['question'], form=form)


@user_view.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('bbs_index.index'))


@user_view.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.is_submitted():
        if not form.validate():
            return jsonify({'status': 50001, 'msg': str(form.errors)})
        try:
            utils.verify_num(form.vercode.data)
        except Exception as e:
            return '<h1>{}</h1>'.format(e), 404
        user = mongo.db.users.find_one({'email': form.email.data})
        if user:
            return jsonify({'status': 50000, 'msg': '该邮箱已经注册'})
        user = {
            'is_active': False,
            'coin': 0,
            'email': form.email.data,
            'username': form.username.data,
            'vip': 0,
            'reply_count': 0,
            'avatar': url_for('static',
                filename='images/avatar/{}.jpg'.format(randint(0, 12))),
            'password': generate_password_hash(form.password.data),
            'created_at': datetime.utcnow()
        }
        insert_result = mongo.db.users.insert_one(user)
        # utils.send_email(form.email.data, '你激活了',
        #                  body='你已经成功注册了账号，同时完成了发送邮件功能！')
        # mongo.db.users.update_one(
        #     {'username': form.username.data}, {'$set': {'is_active': True}}
        # )
        send_active_email(form.username.data, insert_result.inserted_id, form.email.data)
        return redirect(url_for('.login'))
    ver_code = utils.gen_verify_num()
    return render_template(
        'user/register.html',
        ver_code=ver_code['question'],
        form=form
    )


@user_view.route('/<ObjectId:user_id>')
@login_required
def user_home(user_id):
    user = mongo.db.users.find_one_or_404({'_id': user_id})
    return render_template('user/home.html', user=user)


@user_view.route('/messsage')
@user_view.route('/message/page/<int:pn>')
@login_required
def user_message(pn=1):
    user = current_user.user
    if user.get('unread', 0) > 0:
        mongo.db.users.update({'_id': user['_id']}, {'$set': {'unread': 0}})
    message_page = db_utils.get_page(
        'messages', pn, filter1={'user_id': user['_id']}, sort_by=('_id', -1)
    )
    return render_template(
        'user/message.html', user_page='message', page_name='user', page=message_page
    )


@user_view.route('/message/remove', methods=['POST'])
@login_required
def remove_message():
    user = current_user.user
    if request.values.get('all') == 'true':
        mongo.db.messages.delete_many({'user_id': user['_id']})
    elif request.values.get('id'):
        msg_id = ObjectId(request.values.get('id'))
        mongo.db.messages.delete_one({'_id': msg_id})
    return jsonify(models.BaseResult())


@user_view.route('/set', methods=['GET', 'POST'])
@login_required
def user_set():
    if request.method == 'POST':
        include_keys = ['username', 'avatar', 'desc', 'city', 'sex']
        data = request.values
        update_data = {}
        for key in data.keys():
            if key in include_keys:
                update_data[key] = data.get(key)
        mongo.db.users.update(
            {'_id': current_user.user['_id']}, {'$set': update_data}
        )
        return jsonify('修改成功')
    return render_template(
        'user/set.html', user_page='set', page_name='user', title='基本设置'
    )


# @user_view.route('/repass', methods=['POST'])
# def user_repass():
#     if not current_user.is_authenticated:
#         redirect(url_for('user.login'))
#     pwd_form = forms.ChangePassWordForm()
#     if not pwd_form.validate():
#         return jsonify(
#             models.R.fail(
#                 code_msg.PARAM_ERROR.get_msg(),
#                 str(pwd_form.errors)
#             )
#         )
#     nowpassword = pwd_form.nowpassword.data
#     password = pwd_form.password.data
#     user = current_user.user
#     if not models.User.validate_login(user['password'], nowpassword):
#         raise Exception(code_msg.PASSWORD_ERROR)
#     mongo.db.users.update(
#         {'_id': user['_id']}, {'$set': {'password': generate_password_hash(password)}}
#     )
#     return jsonify(models.R.ok())


@user_view.route('/active', methods=['GET', 'POST'])
def user_active():
    if request.method == 'GET':
        code = request.values.get('code')
        if code:
            user_id = mongo.db.active_codes.find_one(
                {'_id': ObjectId(code)}
            ).get('user_id')
            if user_id:
                mongo.db.active_codes.delete_many({'user_id': ObjectId(user_id)})
                mongo.db.users.update(
                    {'_id': user_id}, {'$set': {'is_active': True}}
                )
                user = mongo.db.users.find_one({'_id': ObjectId(user_id)})
                login_user(models.User(user))
                return render_template('user/activate.html')
        if not current_user.is_authenticated:
            abort(403)
        return render_template('user/activate.html')
    user = current_user.user
    mongo.db.active_codes.delete_many({'user_id': ObjectId(user['_id'])})
    send_active_email(user['username'], user['_id'], user['email'])
    return jsonify(code_msg.RE_ACTIVATE_MAIL_SEND.put('action', url_for('user.user_active')))


@user_view.route('/forget', methods=['POST', 'GET'])
def user_pass_forget():
    code = request.args.get('code')
    mail_form = forms.SendForgetMailForm()
    if mail_form.is_submitted():
        if not mail_form.validate():
            return jsonify(
                models.R.fail(
                    code_msg.PARAM_ERROR.get_msg(),
                    str(mail_form.errors)
                )
            )
        email = mail_form.email.data
        ver_code = mail_form.vercode.data
        utils.verify_num(ver_code)
        user = mongo.db.users.find_one({'email': email})
        if not user:
            return jsonify(code_msg.USER_NOT_EXIST)
        send_active_email(user['username'], user_id=user['_id'], email=email, is_forget=True)
        return jsonify(code_msg.RE_PWD_MAIL_SEND.put('action', url_for('user.login')))
    has_code = False
    user = None
    if code:
        active_code = mongo.db.active_codes.find_one({'_id': ObjectId(code)})
        if not active_code:
            return render_template(
                'user/forget.html', page_name='user', has_code=True, code_invalid=True
            )
        has_code = True
        user = mongo.db.users.find_one({'_id': active_code['user_id']})
    ver_code = utils.gen_verify_num()

    return render_template(
        'user/forget.html', page_name='user', ver_code=ver_code['question'],
        code=code, has_code=has_code, user=user
    )


@user_view.route('/repass', methods=['POST'])
def user_repass():
    if 'email' in request.values:
        pwd_form = forms.ForgetPasswordForm()
        if not pwd_form.validate():
            return jsonify(models.R.fail(code_msg.PARAM_ERROR.get_msg(), str(pwd_form.errors)))
        email = pwd_form.email.data
        ver_code = pwd_form.vercode.data
        code = pwd_form.code.data
        password = pwd_form.password.data
        utils.verify_num(ver_code)
        active_code = mongo.db.active_codes.find_one_or_404({'_id': ObjectId(code)})
        mongo.db.active_codes.delete_one({'_id': ObjectId(code)})
        user = mongo.db.users.update(

fly_bbs/plugins/__init__.py
from .whoosh import WhooshSearcher

fly_bbs/templates/_list_item.html
{% set item_user = mongo_find_one('users', {'_id': item.user_id}) or {} %}
{% set item_catalog = mongo_find_one('catalogs', {'_id': item.catalog_id}) %}

<li>
  <a href="/user/{{ item_user._id }}" class="fly-avatar">
    <img
      src="{{ item_user.avatar or '/static/images/avatar/1.jpg' }}"
      alt="{{ item_user.username }}"
    />
  </a>
  <h2>
    <a class="layui-badge">{{ item_catalog.name }}</a>
    <a href="/post/{{ item._id }}">{{ item.title }}</a>
  </h2>
  <div class="fly-list-info">
    <a href="/user/{{ item_user._id or 'none'}}" link>
      <cite>{{ item_user.username or '无名' }}</cite>
      {% if item_user.renzheng %}
      <i class="iconfont icon-renzheng">{{ item_user.renzheng }}</i>
      {% endif %} {% if item_user.get('vip', 0) > 0 %}
      <i class="layui-badge fly-badge-vip">VIP{{ item_user.vip }}</i>
      {% endif %}
    </a>
    <span>{{ item.create_at|mongo_date_str }}</span>
    <span class="fly-list-kiss layui-hide-xs" title="悬赏金币">
      <i class="iconfont icon-jifen"></i>{{ item.get('reward', 0) }}
    </span>
    {% if item.is_closed %}
    <span class="layui-badge fly-badge-accept layui-hide-xs">已结</span>
    {% endif %}
    <span class="fly-list-nums"><i class="iconfont 1"></i></span>
  </div>
  <div class="fly-list-badge">
    {% if item.is_top %}
    <span class="layui-badge layui-bg-black">置顶</span>
    {% endif %} {% if item.is_cream %}
    <span class="layui-badge layui-bg-red">精帖</span>
    {% endif %}
  </div>
</li>

fly_bbs/templates/base.html
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8" />
  <title>
    {% block title %}HOME{% endblock %} - {{ get_option('title').val or 'PyFly'
    }}
  </title>
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1,
      maximum-scale=1"
  />
  <!-- 网站关键字 -->
  <meta name="keywords" content="{{ get_option('keywords').val }}" />
  <!-- 网站描述 -->
  <meta name="description" content="{{ get_option('description').val }}" />
  <link rel="stylesheet" href="/static/layui/css/layui.css" />
  <link rel="stylesheet" href="/static/css/global.css" />
  {% block other_res %} {% endblock %}
</head>
  <body>
  <div class='fly-header layui-bg-black'>
    <div class="layui-container">
      <a class="fly-logo" href="/">
        <img src="/static/images/logo.png" alt="layui">
      </a>
      <ul class="layui-nav fly-nav layui-hide-xs">
        <li class="layui-nav-item layui-this">
          <a href="#">交流<i class="layui-icon"></i>  </a>
        </li>
        <li class="layui-nav-item layui-this">
          <a href="#">提问<i class="layui-icon"></i>  </a>
        </li>
      </ul>
      <ul class="layui-nav fly-nav-user">
  <!-- 判断用户是否登录 -->
  {% if current_user.is_authenticated %}
  <li class="layui-nav-item">
    <a class="fly-nav-avatar" href="javascript:;">
      <cite class="layui-hide-xs">{{ current_user.user.username }}</cite>
      {% if current_user.user.renzheng %}
      <i
        class="iconfont icon-renzheng"
        title="{{ current_user.user.renzheng }}"
      ></i>
      {% endif %} {% if current_user.user.get('vip', 0) > 0 %}
      <i class="layui-badge fly-badge-vip">VIP{{ current_user.user.vip }}</i>
      {% endif %}
      <img src="{{ current_user.user.avatar }}" />
    </a>
    <dl class="layui-nav-child">
      {#
  <dd>
    <a href="{{ url_for('user.user_set') }}"
      ><i class="layui-icon">&#xe620;</i>基本设置</a
    >
  </dd>
  }
  <dd>
    <a href="{{ url_for('user.user_message') }}"
      ><i class="iconfont icon-tongzhi" style="top: 4px;"></i>我的消息</a
    >
  </dd>
  #}
  <dd>
    <a href="{{ url_for('user.user_home', user_id=current_user.user._id) }}"
      ><i class="layui-icon" style="margin-left: 2px; font-size: 22px;"
        >&#xe68e;</i
      >我的主页</a
    >
  </dd>
  <hr style="margin: 5px 0;" />
  <dd>
    <a href="{{ url_for('user.logout') }}" style="text-align: center;">退出</a>
  </dd>
</dl>
  </li>
  {% if current_user.user.get('unread', 0) > 0 %}
  <li class="layui-nav-item">
    <!-- a href="{#{ url_for('user.user_message') }#}">
                <span class="layui-badge">{#{ current_user.user.unread }#}</span>
              </a -->
  </li>
  <!-- 如果没有登录，显示登录和注册按钮 -->
  {% elif get_option('open_user').val == 1 %}
<li class="layui-nav-item">
  <a class="iconfont icon-touxiang layui-hide-xs" href="#"></a>
</li>
<li class="layui-nav-item">
  <a href="/user/login">登录</a>
</li>
<li class="layui-nav-item">
  <a href="/user/register">注册</a>
</li>
{% endif %}
        {% endif %}
</ul>
    </div>
  </div>
{% block body %}
{% endblock %}
<div class="fly-footer">
  <p>{{ get_option('footer').val or 'Powerrr by PyFly' }}</p>
  <p>
    &copy; Copyright 2020 by
    <a href="#">Experimental Project</a>
  </p>
</div>
<script src="/static/layui/layui.js"></script>
<script>
  layui.cache.page = "{{ page_name if page_name else '' }}";
  layui.cache.user = {
      username: "{{ current_user.user['username'] if current_user.is_authenticated else '游客'}}",
      uid: "{{ current_user.user['_id'] if current_user.is_authenticated }}",
      avatar: "{{ current_user.user['avatar'] if current_user.is_authenticated}}",
      experience: "{{ current_user.user['coin'] if current_user.is_authenticated else '0'}}",
      sex: "{{ current_user.user.get('sex', '未知') if current_user.is_authenticated else '未知'}}"
  };
  layui.config({
      version: "3.0.0"
      , base: '/static/mods/' //这里实际使用时，建议改成绝对路径
  }).extend({
      fly: 'index'
  }){% block fly_use %}.use('fly'); {% endblock %}
</script>
{% block other_js %} {% endblock %}
</body>
</html>

fly_bbs/templates/posts.html
{% extends 'base.html' %} {% block body %}
<div class="fly-panel fly-column">
  <div class="layui-container">
    <ul class="layui-clear">
      <li class="layui-hide-xs {{ 'layui-this' if is_index }}">
        <a href="/">综合</a>
      </li>
      {% for item in get_list('catalogs', sort_by=('sort_key', 1)) %}
      <li class="layui-hide-xs {{ 'layui-this' if catalog_id == item._id }}">
        <a href="/catalog/{{ item._id }}">{{ item.name }}</a>
      </li>
      {% endfor %}
      <li class="layui-hide-xs layui-hide-sm layui-show-md-inline-block">
        <span class="fly-mid"></span>
      </li>
      {% if current_user.is_authenticated %}
      <li class="layui-hide-xs layui-hide-sm layui-show-md-inline-block">
        <a href="#">我发表的贴</a>
      </li>
      <li class="layui-hide-xs layui-hide-sm layui-show-md-inline-block">
        <a href="#">我收藏的贴</a>
      </li>
      {% endif %}
    </ul>
    <div class="fly-column-right layui-hide-xs">
      <span class="fly-search"><i class="layui-icon"></i></span>
      <a href="{{ url_for('bbs_index.add') }}" class="layui-btn">发表新帖</a>
    </div>
    <div
      class="layui-hide-sm layui-show-xs-block"
      style="margin-top: -10px; padding-bottom: 10px; text-align: center;"
    >
      <a href="{{ url_for('bbs_index.add') }}" class="layui-btn">发表新帖</a>
    </div>
  </div>
</div>
<div class="layui-container">
  <div class="layui-row layui-col-space15">
    {% block content %} {% endblock %}
    <div class="layui-col-md4">
      {% if is_index %}
      <div class="fly-panel">
        <h3 class="fly-panel-title">温馨通道(暂无内容)</h3>
        <ul class="fly-panel-main fly-list-static">
          {% for item in get_list('passageways', sort_by=('sort', -1)) %}
          <li>
            <a href="{{ item.url }}" target="_blank">{{ item.name }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
      {% if current_user.is_authenticated %}
      <div class="fly-panel fly-signin">
        <div class="fly-panel-title">
          签到
          <i class="fly-mid"></i>
          <a href="javascript:;" class="fly-link" id="LAY_signinHelp">说明</a>
        </div>
        <div class="fly-panel-main fly-signin-main"></div>
      </div>
      {% endif %}
      <div class="fly-panel fly-rank fly-rank-reply" id="LAY_replyRank">
        <h3 class="fly-panel-title">回贴榜</h3>
        <dl>
          <!--<i class="layui-icon fly-loading">&#xe63d;</i>-->
          {% for item in get_list('users', sort_by=('reply_count',-1), size=12)
          %}
          <dd>
            <a href="#">
              暂未实现
            </a>
          </dd>
          {% else %}
          <div class="fly-none">没有相关数据</div>
          {% endfor %}
        </dl>
      </div>
      {% endif %}
      <dl class="fly-panel fly-list-one">
        <dt class="fly-panel-title">本周热议</dt>
        {% for item in get_list('posts', sort_by=('comment_count',-1), size=10,
        filter1={'create_at':{'$gte': date_cal(now(), 7, False)}}) %}
        <dd>
          <a href="/post/{{ item._id }}">{{ item.title }}</a>
          <span
            ><i class="iconfont icon-pinglun1"></i> {{ item.get('comment_count',
            0) }}</span
          >
        </dd>
        {% else %}
        <div class="fly-none">没有相关数据</div>
        {% endfor %}
      </dl>
    </div>
  </div>
</div>
{% endblock %}